<?php
    $lang['number']   = 'Číslo objednávky';
    $lang['date']     = 'Datum vystavení';
    $lang['time']     = 'Čas vystavení';
    $lang['due']      = 'Datum splatnosti';
    $lang['due_fill'] = 'Datum uskutečnění plnění';
    $lang['to']       = 'Odběratel';
    $lang['from']     = 'Dodavatel';
    $lang['product']  = 'Produkt';
    $lang['qty']      = 'Množství';
    $lang['price']    = 'Cena';
    $lang['discount'] = 'Sleva';
    $lang['vat']      = 'DPH';
    $lang['total']    = 'Celkem';
    $lang['page']     = 'Strana';
    $lang['page_of']  = 'z';

