<?php
    $lang['number']   = 'Order number';
    $lang['date']     = 'Billing date';
    $lang['time']     = 'Billing time';
    $lang['due']      = 'Due date';
    $lang['to']       = 'Customer';
    $lang['from']     = 'Seller';
    $lang['product']  = 'Product';
    $lang['qty']      = 'Quantity';
    $lang['price']    = 'Price';
    $lang['discount'] = 'Discount';
    $lang['vat']      = 'Vat';
    $lang['total']    = 'Total';
    $lang['page']     = 'Page';
    $lang['page_of']  = 'of';
